### ISSUE TITLE
URL in Event title

### ISSUE THREAD

**Issue by ghost** [gctools-outilsgc/gccollab#165]
Hi,

Someone created an event using an URL as the title and the link doesn't work.

Look for an event called "http://www.ontraduitaquebec.com/accueil/" (July 23 to 26) in https://gccollab.ca/event_calendar/list/

If you try to click on it, you get to an error page. The link is wrong: https://gccollab.ca/event_calendar/view/19998/ennullfrhttpwwwontraduitaquebeccomaccueil

**Comment by markwooff** [comment]
Hi @gabrielcossette-ca, thanks for flagging this. Looks like it was a problem with the event permissions rather than an issue with the URL. This event is part of a closed group and shouldn't have been displayed on the public Event Calendar page.

The permissions have been updated to reflect the closed group.

**Comment by ghost** [comment]
Ok, thanks for the explanation. Weird that I didn't get the "Access Denied" page?

**Comment by markwooff** [comment]
Agreed.. when I have time I might dive into the Event Calendar code a bit more. Elgg baffles me from time to time.
