### ISSUE TITLE
Inconsistency in language to action Search

### ISSUE THREAD

**Issue by ghost** [gctools-outilsgc/gccollab#188]
1.  To action a top level search, you enter search terms and _click on magnifying glass (or hit enter)_

2. on Member Search, you enter search terms and _click on Search_

3.  On Group Search you enter search terms and _click on Go_

**Comment by markwooff** [comment]
Seems as though each of these search areas were built separately & perhaps consistency was lost in the process. I've made the changes so that each of these areas use the same language & look:

1. Uses the text "Search GCcollab" as placeholder until user enters a value. The magnifying glass is used to represent the search action.

![image](https://user-images.githubusercontent.com/5591488/29851897-cff18eee-8d04-11e7-8310-e0f6ec3bb8ca.png)

2. Input field now uses the text "Search GCcollab" as placeholder until user enters a value. The text "Search" is used with the magnifying glass to represent the search action.

![image](https://user-images.githubusercontent.com/5591488/29851921-fccccb18-8d04-11e7-81d5-9f2eabb5ee47.png)

3. Input field now uses the text "Search GCcollab" as placeholder until user enters a value. Now uses the text "Search" instead of "Go" along with the magnifying glass to represent the search action.

![image](https://user-images.githubusercontent.com/5591488/29851962-4028a2f6-8d05-11e7-8d6a-13599187eb22.png)

**Comment by ghost** [comment]
Thank you !
