### ISSUE TITLE
Error in Widget Title for Group

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#206]
Coding characters appear in Group Title within widget. Language code can be seen in widget view. 

Suspected this is specifically for bilingual content? See below:

![image](https://user-images.githubusercontent.com/29754185/30481328-ff96b914-99eb-11e7-851a-4a6229fc893d.png)

**Comment by markwooff** [comment]
Noticed a couple of groups with this issue, specifically [The Future of Government - exploring how government could change over the next 10-15 years](https://gccollab.ca/groups/profile/5301/enthe-future-of-government-exploring-how-government-could-change-over-the-next-10-15-yearsfr) and [User Experience Design](https://gccollab.ca/groups/profile/5563/enuser-experience-designfr). Issue was due to the titles not being saved correctly, I've gone in as admin and just re-saved the groups to clear this issue.

![image](https://user-images.githubusercontent.com/5591488/30483784-2a281876-99f6-11e7-8fd2-c7fd378f8273.png)
