### ISSUE TITLE
Opportunity Platform not creating new opportunities

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#223]
Linked to https://github.com/Phanoix/gccollab-help/issues/7

As a user, creating a new Opportunity it appears I've done everything right. I get a green confirmation notification pop up that indicates that my Opportunity has been created (but only lasts about 1-2 seconds so I can't read it. When I go to the list of Opportunities- my post is not there. I have tested this twice and a user initially reported it.

The details of my test Opportunity:
![image](https://user-images.githubusercontent.com/29754185/31957319-6572750e-b8bc-11e7-9cab-02da3472dcc2.png)

It appears the longer green pop-up only appears when I add skills - thus am redirected to the 'users with these skills' page. This pop up should stay longer than 2 seconds:
![image](https://user-images.githubusercontent.com/29754185/31957452-d19a95ea-b8bc-11e7-81a9-c49eab0639c4.png)

**Comment by markwooff** [comment]
@klecuyer thanks for flagging this issue today. Would have been a quick fix if I had some free time earlier!

The issue was that a script for preventing duplicate Opportunities that was run on GCconnex was not run on GCcollab. After running it, this issue with posting new Opportunities works as expected.

Thanks,
Mark
