### ISSUE TITLE
Page not found when logging in from mobile site

### ISSUE THREAD

**Issue by PhilAndrecheck** [gctools-outilsgc/gccollab#225]
When logging in to GCcollab.ca in English from the Chrome browser for my Android 7 device, I get logged in but land on a "Page not found" page.
Screen cap attached:
![pagenotfoundcollabmobile](https://user-images.githubusercontent.com/22220521/32004590-212ec082-b970-11e7-9758-49ecf512dee0.png)

**Comment by markwooff** [comment]
@PhilAndrecheck could you copy and paste the URL that is in your browser when this happens? From the screenshot I can see `https://gccollab.ca/mod/wet4...` which makes me think you're being redirected somewhere.

**Comment by LemieuxGen** [comment]
@markwooff Looks like the issue with Page not found is also on the Web applicatin. From the GCcollab login page, if I login, I get the "Page not found". This is not caused by a redirect. I was able to replicate multiple times. If I do a hard refresh, this issue happens every time I try to log in. 
![collab_login_page not found](https://user-images.githubusercontent.com/15378977/32495892-7febcb72-c395-11e7-877f-39acf72387d8.PNG)
URL in browser is: https://gccollab.ca/_graphics/favicon-collab.svg

**Comment by markwooff** [comment]
I believe this is the same issue that @PhilAndrecheck had on mobile. I've just made a code change and am not seeing this anymore, can you confirm @LemieuxGen ?

**Comment by LemieuxGen** [comment]
@markwooff Just tried, and it still giving me a page not found.

**Comment by markwooff** [comment]
@sdkibb put in a fix with https://github.com/gctools-outilsgc/gcconnex/commit/e05f618392e493a8281d17ea22f043508461613a, will continue testing but haven't seen the error message again.

**Comment by piet0024** [comment]
After a bit of testing it seems things like image path URLs are getting saved into the forward URL session when a user is going through the site not logged in. The login action is taking this URL from the session and forwarding to it after login, but since the path to a file is not an actual page you get the 404. 

I'm still looking into why these URLs are getting saved into the session, just providing a bit of an update.

**Comment by markwooff** [comment]
Thanks @piet0024 - let me know if you need any changes or testing done.

**Comment by piet0024** [comment]
This is a similar issue on connex so if I resolve it there I'll link it to this issue. I'll keep you posted 👌

**Comment by PhilAndrecheck** [comment]
I think we've fixed the issue! And by we I mean @piet0024 and @markwooff of course!
Works on Android 7, Chrome and Samsung browser.
Thanks so much!
