### ISSUE TITLE
Closed content (user doesn't have access) still appearing in communities

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#232]
As a user, I want to see content I have access to.
As a group owner, I don't want my closed content to appear in communities to people who aren't supposed to have access to them.

A user is reporting that most content he tried to access on GCcollab under the Tech Community gives him an error message that this content has been removed or he does not have persmission to view it. Can we change the way this displays to users so that they only see content that can open? Or is this a rebuild conversation?
![image](https://user-images.githubusercontent.com/29754185/32953794-4ba79d2c-cb7f-11e7-8706-fd25b5da9441.png)

Linked to https://github.com/Phanoix/gccollab-help/issues/17

**Comment by markwooff** [comment]
Just took a look and can see what is happening here. There are some items such as files that are added to a Group and set to viewable by all "Members logged into GCcollab". However this file itself sits in a closed group which would give your error message when trying to view it in the group.

This could probably be fixed by putting in a check to see if the item being displayed on the community page sits in a group, and if it does, check if the user has access to that group. Will see if I can get to this during this sprint.

**Comment by markwooff** [comment]
Turned out to be an issue with the items themselves not set to the right access level, the code behind the community pages is correct. I've manually set those items in a closed group to have "group only access". Can reply to user saying these items should no longer appear.
