### ISSUE TITLE
Language (typo): Carrefour de carriere GCconnex & GCcollab

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#368]
![image](https://user-images.githubusercontent.com/29754185/44405473-5305d980-a527-11e8-8614-472dff1bfff1.png)

This is misspelled in both GCconnex and GCcollab.

Should read: "Bienvenue au Carrefour de carrière".  
Link : https://gccollab.ca/missions/main 
Link: https://gcconnex.gc.ca/missions/main

**Comment by klecuyer** [comment]
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/4804

**Comment by Steph4104** [comment]
I found other potential error, correct me if I'm wrong.

When invite a new user to career (change 'par la Carrefour' to 'par le Carrefour'?)
![image](https://user-images.githubusercontent.com/15112568/45762373-38914f80-bbfc-11e8-893e-8c0cd300e388.png)

Bottom of the main page of Carrer (Change 'La Carrefour' to 'Le Carrefour'?)
![image](https://user-images.githubusercontent.com/15112568/45762483-73938300-bbfc-11e8-8b5b-9caefc64e0c8.png)

Also, in the notification (change 'sur la Carrefour' to 'sur le Carrefour'?)
![image](https://user-images.githubusercontent.com/15112568/45762909-6b881300-bbfd-11e8-9c55-baae5cbc33bf.png)

In the digest, when more than one (change 'de la Carrefour' to 'du Carrefour'?)
![image](https://user-images.githubusercontent.com/15112568/45763172-f49f4a00-bbfd-11e8-88ea-f25a0cdab9a4.png)

In notification settings (change 'dans la Carrefour' to 'dans le Carrefour'?)
![image](https://user-images.githubusercontent.com/15112568/45763372-4f38a600-bbfe-11e8-9505-e4b78127d7ef.png)

When you edit the Opt In section in your profil (change 'pour la Carrefour' to 'pour le Carrefour'?)
![image](https://user-images.githubusercontent.com/15112568/45763504-945cd800-bbfe-11e8-8c5b-198a20b95299.png)


@LemieuxGen , @klecuyer , let me know if we need to change all of them or not. Otherwise, I will just change the one in the Welcome message.

**Comment by LemieuxGen** [comment]
@Steph4104 thanks for finding these. Yes, please proceed with the changes noted above.
