### ISSUE TITLE
Add Auto Join Group Based on Email Extension

### ISSUE THREAD

**Issue by sdkibb** [gctools-outilsgc/gccollab#40]
We need a plugin that will automatically add existing and new users to a group or groups based on email extension.

**Comment by JOutram77** [comment]
Curious, what's an example group that would be applicable to all users of a specific email extension?

**Comment by sdkibb** [comment]
A specific dept or initiative wanting to collaborate specifically with a
province or school.it was the most used feature in GCForums.

**Comment by markwooff** [comment]
@sdkibb @JOutram77 just spoke with Chris on this. Would be great if we could add Groups that would be auto-joined (or at least suggested during onboarding) for the variety of members that are joining the platform.

An example would be a **Carleton Students** group for any user with a @carleton.ca email extension.

**Comment by markwooff** [comment]
Feature has been built into the admin panel with 4972c19ca0ff8be8ee72e9b071c0d5a9dd9b11f7 so that specific organizations can be set to be automatically joined to specific groups. The new plugin also allows the admin to set up automatic joins for all new user registrations and for all users who create a group:

![image](https://cloud.githubusercontent.com/assets/5591488/23757332/7ddd5918-04b4-11e7-938a-68e1dc09d482.png)

![image](https://cloud.githubusercontent.com/assets/5591488/23757441/de09d424-04b4-11e7-96b6-1ea44822d414.png)
