### ISSUE TITLE
Investigate / fix returns from /groups/all, blog/all

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gccollab#46]
https://gccollab.ca/groups/all returns discussions
https://gccollab.ca/blog/all returns full blogs (think this should return card snippets as per groups above)

Blogs also have "blog_tools:toggle:feature" in the action icons after  post comments and before edit.

**Comment by markwooff** [comment]
I'm hoping these issues will be fixed when the latest changes from GCconnex get merged into GCcollab as it appears these have been resolved there.

The "blog_tools:toggle:feature" text is appearing because the Blog Tools plugin is currently inactive, is there any reason it should not be active? @sdkibb @JOutram77

**Comment by markwooff** [comment]
All updates from GCconnex have been merged into GCcollab, changes can be seen on the updated DEV site at https://dev.gccollab.ca/

Will merge these changes into PROD overnight as there will be a little downtime due to new plugins.
