### ISSUE TITLE
Group filtering not working

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gccollab#81]
From gccollab.ca/groups/all - selecting Popular or More>Latest Discussion seems to return Newest groups.

Also, please confirm results for Filtering More>Suggested Groups.

**Comment by markwooff** [comment]
Bug has been fixed so that the Group page tabs will display the proper information. The Suggested tab appears to be working as it should.. there is only one Suggested Group set in the backend so the list will appear empty if the user is already part of the GCcollab Café group:

![image](https://cloud.githubusercontent.com/assets/5591488/22884909/23414d68-f1c5-11e6-866e-cafb6f4c641b.png)
