### ISSUE TITLE
Email Fix - Change the source of the users identity

### ISSUE THREAD

**Issue by JOutram77** [gctools-outilsgc/gccollab#86]
In an email received to notify me of a blog posting gave the user name based on the user's email address. Can we change this to pull from the user's display name?

<img width="526" alt="email fix - screenshot" src="https://cloud.githubusercontent.com/assets/22943228/23002214/85941510-f3b7-11e6-952a-69658878b140.PNG">

This isn't a problem when pulling this content from government email addresses, but it is an issue when pulling from other email addresses such as universities.

**Comment by ToferC** [comment]
The username is pulled in all referrals from the user as far as I know. Q:
do we auto-generated usernames for GCcollab? If so, how do we do it?
Thanks!

**Comment by markwooff** [comment]
The username is automatically generated from the [Register](https://gccollab.ca/register) page using the same method as GCconnex: looks at the user's email address for text and if that name is already being used as a username, it will append an incremented number to the username.

Jeff brings up a good point that not all email addresses used for GCcollab will have the same **firstname.lastname** structure as government email addresses. All links referring to a user's profile must continue to use the username, but the email notifications could use the display name to avoid confusion.

**Comment by ToferC** [comment]
I think it might be easier to change the way we set the username than
switching the way it displays in multiple places and the thing that folks
need to know to @mention.

The auto-username was added to keep folks from using pseudonyms and because
of the standard first.last@org.gc.ca email structure of the GC.

As Collab users can make anything their email address, the decision to
generate username based on this gets shaky.

I'd rather investigate changing username to a combination of first.last
from display name and doing an bit of validation to ensure that people acre
on track for the most part.

For the rest, we deal with violations through friendly reminders. Thoughts?

**Comment by ToferC** [comment]
As an aside, this is why framing issues as user stories is important. It gives more context to developers on what the issue by why they want it vs. just what they wants - which may not mesh with the applications system, philosophy or priorities.

**Comment by markwooff** [comment]
Usernames will be generated based on the Display Name provided by the user upon registration, as discussed.
